baseurl                 = "https://obi.obiknows.co/"               # Your domain name. Must end with "/"
# languageCode            = "en-us"
title                   = "its Obi"
theme                   = "obi"
googleAnalytics         = "UA-118672950-1"             # Tracking code, eg. "UA-111111111-1"

[params]
    dateform            = "Mon Jan 02, 2006"
    dateformfull        = "Mon Jan 2 2006 15:04:05 EST"
    # dateform            = "Mon May 14, 2018"
    # dateformfull        = "Mon May 14, 2018 1:04:05 EST"
    favicon             = "/obi.ico"
    pygmentsUseClassic  = true
    pygmentsStyle       = "monokai"                     # https://help.farbox.com/pygments.html
    pygmentsCodefences  = true
    homepage            = "ğŸ¡"                        # What to call the home page link
    galleryFolder       = "images/"                     # Where you've put your images, after "/content/gallery/"
    clickablePhotos     = true                          # Allow links to the full size images
    footerText          = "Obi Knows Co."

# Metadata
    description         = "Obi Knows Personal Site"            # Max 160 characters show in search results
    twitterCard         = "summary_large_image"         # Card value â€œsummaryâ€, â€œsummary_large_imageâ€, â€œappâ€, or â€œplayerâ€
    primaryImage        = "/tn.png"                     # Image that shows on Twitter cards and OpenGraph links

# Front Page Sections

[[params.mainMenu]]
    link = "/code"
    text = "obi knows' code ğŸ’»"

[[params.mainMenu]]
    link = "/beats"
    text = "obi got beats ğŸ¥"

[[params.mainMenu]]
    link = "/research"
    text = "obi does research ğŸ”¬"


[[params.mainMenu]]
    link = "/pics"
    text = "obi takes pics ğŸ“¸"

[[params.mainMenu]]
    link = "/posts"
    text = "obi writes words âœğŸ¿"

[[params.mainMenu]]
    link = "/about"
    text = "who is obi? ğŸ"
    
